name: Nightly Release CLI

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        type: string
        description: "Distinct ID"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

  build:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux-aarch64
            os: ubuntu-18.04
            target: aarch64-unknown-linux-gnu
            bin: runtipi-cli
            name: runtipi-cli-linux-aarch64
            command: build

          - release_for: linux-x86_64
            os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            bin: runtipi-cli
            name: runtipi-cli-linux-x86_64
            command: build

          # - release_for: macOS-aarch64
          #   os: macOS-latest
          #   target: aarch64-apple-darwin
          #   bin: runtipi-cli
          #   name: runtipi-cli-Darwin-aarch64
          #   command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version in src/assets/VERSION
        run: |
          echo "nightly" > src/assets/VERSION

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload CLI
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Move artifacts
        run: for dir in runtipi-cli-linux-*; do mv "$dir/runtipi-cli" "${dir}.cli" && rm -rf "$dir" && mv "${dir}.cli" "$dir"; done

      - name: Compress artifacts
        run: for file in runtipi-cli-linux-*; do tar -czvf "$file.tar.gz" "$file" && rm -rf "$file"; done

      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          rm: true
          files: runtipi-cli-*
